const GET_USER_FRIENDS_PENDING = 'GET_USER_FRIENDS_PENDING';
const GET_USER_FRIENDS_FULFILLED = 'GET_USER_FRIENDS_FULFILLED';
const GET_USER_FRIENDS_REJECTED = 'GET_USER_FRIENDS_REJECTED';
const GET_OTHER_USERS_PENDING = 'GET_OTHER_USERS_PENDING';
const GET_OTHER_USERS_FULFILLED = 'GET_OTHER_USERS_FULFILLED';
const GET_OTHER_USERS_REJECTED = 'GET_OTHER_USERS_REJECTED';

export {
  GET_USER_FRIENDS_PENDING,
  GET_USER_FRIENDS_FULFILLED,
  GET_USER_FRIENDS_REJECTED,
  GET_OTHER_USERS_PENDING,
  GET_OTHER_USERS_FULFILLED,
  GET_OTHER_USERS_REJECTED,
};
