const GET_USER_FRIENDS_PENDING = 'GET_USER_FRIENDS_PENDING';
const GET_USER_FRIENDS_FULFILLED = 'GET_USER_FRIENDS_FULFILLED';
const GET_USER_FRIENDS_REJECTED = 'GET_USER_FRIENDS_REJECTED';
const GET_OTHER_USERS_PENDING = 'GET_OTHER_USERS_PENDING';
const GET_OTHER_USERS_FULFILLED = 'GET_OTHER_USERS_FULFILLED';
const GET_OTHER_USERS_REJECTED = 'GET_OTHER_USERS_REJECTED';
const ADD_FRIEND_PENDING = 'ADD_FRIEND_PENDING';
const ADD_FRIEND_FULFILLED = 'ADD_FRIEND_FULFILLED';
const ADD_FRIEND_REJECTED = 'ADD_FRIEND_REJECTED';
const GET_MESSAGES_PENDING = 'GET_MESSAGES_PENDING';
const GET_MESSAGES_FULFILLED = 'GET_MESSAGES_FULFILLED';
const GET_MESSAGES_REJECTED = 'GET_MESSAGES_REJECTED';
const SEND_MESSAGE_PENDING = 'SEND_MESSAGE_PENDING';
const SEND_MESSAGE_FULFILLED = 'SEND_MESSAGE_FULFILLED';
const SEND_MESSAGE_REJECTED = 'SEND_MESSAGE_REJECTED';

export {
  GET_USER_FRIENDS_PENDING,
  GET_USER_FRIENDS_FULFILLED,
  GET_USER_FRIENDS_REJECTED,
  GET_OTHER_USERS_PENDING,
  GET_OTHER_USERS_FULFILLED,
  GET_OTHER_USERS_REJECTED,
  ADD_FRIEND_PENDING,
  ADD_FRIEND_FULFILLED,
  ADD_FRIEND_REJECTED,
  GET_MESSAGES_PENDING,
  GET_MESSAGES_FULFILLED,
  GET_MESSAGES_REJECTED,
  SEND_MESSAGE_PENDING,
  SEND_MESSAGE_FULFILLED,
  SEND_MESSAGE_REJECTED,
};
