const POST_USER_LOGIN_PENDING = 'POST_USER_LOGIN_PENDING';
const POST_USER_LOGIN_FULFILLED = 'POST_USER_LOGIN_FULFILLED';
const POST_USER_LOGIN_REJECTED = 'POST_USER_LOGIN_REJECTED';
const CLEAR_STATE = 'CLEAR_STATE';

export {
  POST_USER_LOGIN_PENDING,
  POST_USER_LOGIN_FULFILLED,
  POST_USER_LOGIN_REJECTED,
  CLEAR_STATE,
};
