const POST_USER_LOGIN_PENDING = 'POST_USER_LOGIN_PENDING';
const POST_USER_LOGIN_FULFILLED = 'POST_USER_LOGIN_FULFILLED';
const POST_USER_LOGIN_REJECTED = 'POST_USER_LOGIN_REJECTED';
const POST_USER_REGISTER_PENDING = 'POST_USER_REGISTER_PENDING';
const POST_USER_REGISTER_FULFILLED = 'POST_USER_REGISTER_FULFILLED';
const POST_USER_REGISTER_REJECTED = 'POST_USER_REGISTER_REJECTED';
const USER_LOGOUT_FULFILLED = 'USER_LOGOUT_FULFILLED';
const USER_EXISTS_PENDING = 'USER_EXISTS_PENDING';
const USER_EXISTS_FULFILLED = 'USER_EXISTS_FULFILLED';
const USER_EXISTS_REJECTED = 'USER_EXISTS_REJECTED';
const CLEAR_STATE = 'CLEAR_STATE';

export {
  POST_USER_LOGIN_PENDING,
  POST_USER_LOGIN_FULFILLED,
  POST_USER_LOGIN_REJECTED,
  POST_USER_REGISTER_PENDING,
  POST_USER_REGISTER_FULFILLED,
  POST_USER_REGISTER_REJECTED,
  USER_LOGOUT_FULFILLED,
  USER_EXISTS_PENDING,
  USER_EXISTS_FULFILLED,
  USER_EXISTS_REJECTED,
  CLEAR_STATE,
};
